# Generated by Django 4.2.8 on 2023-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='connect',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='car',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Picture'),
        ),
    ]
